### ISSUE TITLE
casadi compatibility bug

### ISSUE THREAD

**Issue by dthierry** [salvadorgarciamunoz/kipet#4]
We have that for versions > 3.1.0 of casadi the following usually shows for all casadi simulation files

> raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))

If an old version is in fact used this is usually not experienced.

Current solution:
use casadi 3.1.0 instead

Full traceback:
Traceback (most recent call last):
  File "ode_sim.py", line 52, in <module>
    results_casadi = sim.run_sim("cvodes")
  File "/home/dmolinat/kipet/kipet/kipet/sim/CasadiSimulator.py", line 142, in run_sim
    representation = expr.getRepresentation()
  File "/home/dmolinat/kipet/kipet/kipet/local/lib/python2.7/site-packages/casadi/casadi.py", line 8051, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, SX, name)
  File "/home/dmolinat/kipet/kipet/kipet/local/lib/python2.7/site-packages/casadi/casadi.py", line 83, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'SX' object has no attribute 'getRepresentation'

**Comment by dthierry** [comment]
Possible solution https://github.com/casadi/casadi/commit/12aa2625fca29f63834169b3449025a2b39f9b67
i.e. try get_repr (I am testing this tomorrow)

**Comment by dthierry** [comment]
I found out that we can use repr() for the current version of casadi (3.4.0). So I've added the bit:

>                  try:
>                     representation = expr.getRepresentation()
>                 except AttributeError:
>                     representation = expr.repr()
> 
This seems to work. But I am not sure for the versions > 3.1.0 but < 3.4.0.
